--liquibase formatted sql
-- Generated by engine: create data_metric_function changesets

--changeset engine:dmf-dev_fs_db_bronze_dmf_raw_customers_customer_id_not_null-c35d6f2b runOnChange:true labels:data_metric_function,create context:create splitStatements:false endDelimiter:
--comment CREATE data_metric_function DEV_FS_DB.BRONZE.DMF_RAW_CUSTOMERS_CUSTOMER_ID_NOT_NULL

CREATE OR REPLACE DATA METRIC FUNCTION DEV_FS_DB.BRONZE.DMF_RAW_CUSTOMERS_CUSTOMER_ID_NOT_NULL
  (T TABLE("CUSTOMER_ID" VARCHAR))
  RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM T WHERE "CUSTOMER_ID" IS NULL
$$;

--rollback DROP DATA METRIC FUNCTION IF EXISTS DEV_FS_DB.BRONZE.DMF_RAW_CUSTOMERS_CUSTOMER_ID_NOT_NULL;

--changeset engine:dmf-dev_fs_db_bronze_dmf_raw_customers_customer_id_unique-182fe91d runOnChange:true labels:data_metric_function,create context:create splitStatements:false endDelimiter:
--comment CREATE data_metric_function DEV_FS_DB.BRONZE.DMF_RAW_CUSTOMERS_CUSTOMER_ID_UNIQUE

CREATE OR REPLACE DATA METRIC FUNCTION DEV_FS_DB.BRONZE.DMF_RAW_CUSTOMERS_CUSTOMER_ID_UNIQUE
  (T TABLE("CUSTOMER_ID" VARCHAR))
  RETURNS NUMBER
AS
$$
SELECT COUNT(*) - COUNT(DISTINCT "CUSTOMER_ID") FROM T
$$;

--rollback DROP DATA METRIC FUNCTION IF EXISTS DEV_FS_DB.BRONZE.DMF_RAW_CUSTOMERS_CUSTOMER_ID_UNIQUE;
