--liquibase formatted sql
-- Generated by engine: create table changesets

--changeset engine:table-dev_fs_db_bronze_raw_customers-9ddcfd3b labels:table,create context:create
--comment CREATE table DEV_FS_DB.BRONZE.RAW_CUSTOMERS

CREATE TABLE IF NOT EXISTS DEV_FS_DB.BRONZE.RAW_CUSTOMERS (
  "CUSTOMER_ID" VARCHAR(64) NOT NULL COMMENT 'Unique customer identifier',
  "CUSTOMER_NAME" VARCHAR(256) COMMENT 'Full customer name',
  "EMAIL" VARCHAR(256) COMMENT 'Customer email address',
  "COUNTRY_CODE" VARCHAR(3) COMMENT 'ISO country code',
  "CREATED_AT" TIMESTAMP_NTZ COMMENT 'Customer record creation time',
  "LOADED_AT" TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Load timestamp'
)
COMMENT = 'Raw customer master data'
CLUSTER BY ("CREATED_AT");

--rollback DROP TABLE IF EXISTS DEV_FS_DB.BRONZE.RAW_CUSTOMERS;

--changeset engine:table-dev_fs_db_bronze_raw_orders-6b82f873 labels:table,create context:create
--comment CREATE table DEV_FS_DB.BRONZE.RAW_ORDERS

CREATE TABLE IF NOT EXISTS DEV_FS_DB.BRONZE.RAW_ORDERS (
  "ORDER_ID" VARCHAR(64) NOT NULL COMMENT 'Unique order identifier from source system',
  "CUSTOMER_ID" VARCHAR(64) COMMENT 'Customer identifier',
  "ORDER_DATE" TIMESTAMP_NTZ COMMENT 'Order placement timestamp',
  "ORDER_STATUS" VARCHAR(32) DEFAULT 'PENDING' COMMENT 'Order lifecycle status',
  "ORDER_AMOUNT" NUMBER(18,2) COMMENT 'Total order amount in source currency',
  "CURRENCY_CODE" VARCHAR(3) COMMENT 'ISO 4217 currency code',
  "SOURCE_FILE" VARCHAR(512) COMMENT 'Source file name from stage',
  "LOADED_AT" TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Load timestamp',
  "UPDATED_AT" TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Update timestamp'
)
COMMENT = 'Raw orders landed from S3'
CLUSTER BY ("ORDER_DATE");

--rollback DROP TABLE IF EXISTS DEV_FS_DB.BRONZE.RAW_ORDERS;

--changeset engine:table-dev_fs_db_dq_dq_dmf_config-9e70be0a labels:table,create context:create
--comment CREATE table DEV_FS_DB.DQ.DQ_DMF_CONFIG

CREATE TABLE IF NOT EXISTS DEV_FS_DB.DQ.DQ_DMF_CONFIG (
  "CONFIG_ID" VARCHAR(64) NOT NULL COMMENT 'Unique config identifier',
  "TARGET_DATABASE" VARCHAR(128) NOT NULL COMMENT 'Target database name',
  "TARGET_SCHEMA" VARCHAR(128) NOT NULL COMMENT 'Target schema name',
  "TARGET_TABLE" VARCHAR(128) NOT NULL COMMENT 'Target table name',
  "TARGET_COLUMN" VARCHAR(128) COMMENT 'Target column (null for table-level DMFs)',
  "DMF_NAME" VARCHAR(128) NOT NULL COMMENT 'System DMF name: NULL_COUNT, DUPLICATE_COUNT, UNIQUE_COUNT, FRESHNESS',
  "SCHEDULE_MINUTES" NUMBER(18,0) NOT NULL DEFAULT 60 COMMENT 'How often the DMF should evaluate (minutes)',
  "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Whether this DMF assignment is active',
  "CREATED_AT" TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Creation timestamp'
)
COMMENT = 'Snowflake Data Metric Function assignment configuration';

--rollback DROP TABLE IF EXISTS DEV_FS_DB.DQ.DQ_DMF_CONFIG;

--changeset engine:table-dev_fs_db_dq_dq_results-c781e706 labels:table,create context:create
--comment CREATE table DEV_FS_DB.DQ.DQ_RESULTS

CREATE TABLE IF NOT EXISTS DEV_FS_DB.DQ.DQ_RESULTS (
  "RESULT_ID" VARCHAR(64) NOT NULL COMMENT 'Unique result identifier',
  "RULE_ID" VARCHAR(64) NOT NULL COMMENT 'FK to DQ_RULES',
  "RUN_ID" VARCHAR(64) NOT NULL COMMENT 'FK to DQ_RUN_LOG',
  "RUN_TIMESTAMP" TIMESTAMP_NTZ NOT NULL COMMENT 'Execution timestamp',
  "STATUS" VARCHAR(16) NOT NULL COMMENT 'Result status: PASSED, FAILED, ERROR',
  "ACTUAL_VALUE" VARCHAR(4096) COMMENT 'Actual value observed',
  "EXPECTED_VALUE" VARCHAR(4096) COMMENT 'Expected value for comparison',
  "ROWS_FAILED" NUMBER(38,0) DEFAULT 0 COMMENT 'Number of rows that failed the check',
  "SAMPLE_FAILURES" VARIANT COMMENT 'Sample of failing rows (JSON array)',
  "EXECUTION_TIME_MS" NUMBER(18,0) COMMENT 'Rule execution time in milliseconds',
  "ENVIRONMENT" VARCHAR(16) NOT NULL COMMENT 'Environment where rule was executed'
)
COMMENT = 'Data quality execution results'
CLUSTER BY ("RUN_TIMESTAMP");

--rollback DROP TABLE IF EXISTS DEV_FS_DB.DQ.DQ_RESULTS;

--changeset engine:table-dev_fs_db_dq_dq_rules-e42ad775 labels:table,create context:create
--comment CREATE table DEV_FS_DB.DQ.DQ_RULES

CREATE TABLE IF NOT EXISTS DEV_FS_DB.DQ.DQ_RULES (
  "RULE_ID" VARCHAR(64) NOT NULL COMMENT 'Unique rule identifier',
  "RULE_NAME" VARCHAR(256) NOT NULL COMMENT 'Human-readable rule name',
  "RULE_TYPE" VARCHAR(32) NOT NULL COMMENT 'Rule type: NOT_NULL, UNIQUE, ACCEPTED_VALUES, ROW_COUNT_RANGE, REFERENTIAL_INTEGRITY, RECENCY, CUSTOM_SQL, EXPRESSION',
  "SOURCE" VARCHAR(16) NOT NULL DEFAULT 'engine' COMMENT 'Origin: engine (YAML-managed) or user (Streamlit-managed)',
  "TARGET_DATABASE" VARCHAR(128) NOT NULL COMMENT 'Target database name',
  "TARGET_SCHEMA" VARCHAR(128) NOT NULL COMMENT 'Target schema name',
  "TARGET_TABLE" VARCHAR(128) NOT NULL COMMENT 'Target table name',
  "TARGET_COLUMN" VARCHAR(128) COMMENT 'Target column (null for table-level rules)',
  "SEVERITY" VARCHAR(16) NOT NULL DEFAULT 'WARNING' COMMENT 'Severity: CRITICAL, WARNING, INFO',
  "PARAMETERS" VARIANT COMMENT 'JSON parameters specific to rule_type (thresholds values etc)',
  "DESCRIPTION" VARCHAR(1024) COMMENT 'Business description of what the rule checks',
  "OWNER" VARCHAR(128) COMMENT 'Rule owner (team or person)',
  "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Whether the rule is active',
  "CREATED_AT" TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Creation timestamp',
  "UPDATED_AT" TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Last update timestamp'
)
COMMENT = 'Data quality rule definitions (engine-managed and user-managed)';

--rollback DROP TABLE IF EXISTS DEV_FS_DB.DQ.DQ_RULES;

--changeset engine:table-dev_fs_db_dq_dq_run_log-0bdcbe69 labels:table,create context:create
--comment CREATE table DEV_FS_DB.DQ.DQ_RUN_LOG

CREATE TABLE IF NOT EXISTS DEV_FS_DB.DQ.DQ_RUN_LOG (
  "RUN_ID" VARCHAR(64) NOT NULL COMMENT 'Unique run identifier',
  "RUN_TYPE" VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED' COMMENT 'Run type: SCHEDULED, AD_HOC, DEPLOYMENT',
  "START_TIME" TIMESTAMP_NTZ NOT NULL COMMENT 'Run start timestamp',
  "END_TIME" TIMESTAMP_NTZ COMMENT 'Run end timestamp',
  "TOTAL_RULES" NUMBER(18,0) DEFAULT 0 COMMENT 'Total number of rules executed',
  "PASSED" NUMBER(18,0) DEFAULT 0 COMMENT 'Number of rules that passed',
  "FAILED" NUMBER(18,0) DEFAULT 0 COMMENT 'Number of rules that failed',
  "ERRORED" NUMBER(18,0) DEFAULT 0 COMMENT 'Number of rules that errored',
  "TRIGGERED_BY" VARCHAR(128) COMMENT 'Who or what triggered the run',
  "ENVIRONMENT" VARCHAR(16) NOT NULL COMMENT 'Environment where run was executed'
)
COMMENT = 'Data quality run execution log'
CLUSTER BY ("START_TIME");

--rollback DROP TABLE IF EXISTS DEV_FS_DB.DQ.DQ_RUN_LOG;

--changeset engine:table-dev_fs_db_gold_fct_sales-c3e0fcb0 labels:table,create context:create
--comment CREATE table DEV_FS_DB.GOLD.FCT_SALES

CREATE TABLE IF NOT EXISTS DEV_FS_DB.GOLD.FCT_SALES (
  "SALES_SK" NUMBER(38,0) NOT NULL COMMENT 'Surrogate key',
  "ORDER_ID" VARCHAR(64) NOT NULL COMMENT 'Order business key',
  "CUSTOMER_SK" NUMBER(38,0) COMMENT 'FK to dim_customer',
  "ORDER_DATE" DATE NOT NULL COMMENT 'Date of order',
  "REVENUE_USD" NUMBER(18,2) COMMENT 'Revenue converted to USD',
  "ORDER_COUNT" NUMBER(18,0) DEFAULT 1 COMMENT 'Count of orders (for aggregation)',
  "LOADED_AT" TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Load timestamp'
)
COMMENT = 'Sales fact table (Product A)'
CLUSTER BY ("ORDER_DATE");

--rollback DROP TABLE IF EXISTS DEV_FS_DB.GOLD.FCT_SALES;

--changeset engine:table-dev_fs_db_silver_dim_customer-8cd86574 labels:table,create context:create
--comment CREATE table DEV_FS_DB.SILVER.DIM_CUSTOMER

CREATE TABLE IF NOT EXISTS DEV_FS_DB.SILVER.DIM_CUSTOMER (
  "CUSTOMER_SK" NUMBER(38,0) NOT NULL COMMENT 'Surrogate key generated by DBT',
  "CUSTOMER_ID" VARCHAR(64) NOT NULL COMMENT 'Natural key from source',
  "CUSTOMER_NAME" VARCHAR(256) COMMENT 'Full customer name',
  "EMAIL_HASHED" VARCHAR(64) COMMENT 'Hashed email for PII protection',
  "COUNTRY_CODE" VARCHAR(3) COMMENT 'ISO country code',
  "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Active flag',
  "VALID_FROM" TIMESTAMP_NTZ NOT NULL COMMENT 'SCD Type 2 effective from',
  "VALID_TO" TIMESTAMP_NTZ COMMENT 'SCD Type 2 effective to'
)
COMMENT = 'Conformed customer dimension'
CLUSTER BY ("VALID_FROM");

--rollback DROP TABLE IF EXISTS DEV_FS_DB.SILVER.DIM_CUSTOMER;
