--liquibase formatted sql
-- Generated by engine: create file_format changesets

--changeset engine:ff-dev_fs_db_bronze_ff_csv_standard-a5807faf runOnChange:true labels:file_format,create context:create
--comment CREATE file_format DEV_FS_DB.BRONZE.FF_CSV_STANDARD

CREATE OR REPLACE FILE FORMAT DEV_FS_DB.BRONZE.FF_CSV_STANDARD
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ''
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

--rollback DROP FILE FORMAT IF EXISTS DEV_FS_DB.BRONZE.FF_CSV_STANDARD;

--changeset engine:ff-dev_fs_db_bronze_ff_json_standard-4fa65bd9 runOnChange:true labels:file_format,create context:create
--comment CREATE file_format DEV_FS_DB.BRONZE.FF_JSON_STANDARD

CREATE OR REPLACE FILE FORMAT DEV_FS_DB.BRONZE.FF_JSON_STANDARD
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

--rollback DROP FILE FORMAT IF EXISTS DEV_FS_DB.BRONZE.FF_JSON_STANDARD;
