--liquibase formatted sql
-- Generated by engine: create stream changesets

--changeset engine:stream-dev_fs_db_bronze_strm_raw_orders-b57a1358 runOnChange:true labels:stream,create context:create
--comment CREATE stream DEV_FS_DB.BRONZE.STRM_RAW_ORDERS

CREATE OR REPLACE STREAM DEV_FS_DB.BRONZE.STRM_RAW_ORDERS ON TABLE DEV_FS_DB.BRONZE.RAW_ORDERS APPEND_ONLY = TRUE;

--rollback DROP STREAM IF EXISTS DEV_FS_DB.BRONZE.STRM_RAW_ORDERS;
