--liquibase formatted sql
-- Generated by engine: create task changesets

--changeset engine:task-dev_fs_db_dq_tsk_dq_run_finite-4ac321bf runOnChange:true labels:task,create context:create
--comment CREATE task DEV_FS_DB.DQ.TSK_DQ_RUN_FINITE

CREATE OR REPLACE TASK DEV_FS_DB.DQ.TSK_DQ_RUN_FINITE
  WAREHOUSE = WH_DEV_DQ
  SCHEDULE = '60 MINUTE'
AS
CALL DEV_FS_DB.DQ.SP_DQ_EXECUTE_ALL('DEV', 'SCHEDULED');

--rollback DROP TASK IF EXISTS DEV_FS_DB.DQ.TSK_DQ_RUN_FINITE;

--changeset engine:task-dev_fs_db_dq_tsk_dq_sync_dmf-a416a9d9 runOnChange:true labels:task,create context:create
--comment CREATE task DEV_FS_DB.DQ.TSK_DQ_SYNC_DMF

CREATE OR REPLACE TASK DEV_FS_DB.DQ.TSK_DQ_SYNC_DMF
  WAREHOUSE = WH_DEV_DQ
  SCHEDULE = '120 MINUTE'
AS
CALL DEV_FS_DB.DQ.SP_DQ_SYNC_DMF_RESULTS('DEV');

--rollback DROP TASK IF EXISTS DEV_FS_DB.DQ.TSK_DQ_SYNC_DMF;

--changeset engine:task-dev_fs_db_gold_tsk_refresh_sales_hourly-d311f7b8 runOnChange:true labels:task,create context:create
--comment CREATE task DEV_FS_DB.GOLD.TSK_REFRESH_SALES_HOURLY

CREATE OR REPLACE TASK DEV_FS_DB.GOLD.TSK_REFRESH_SALES_HOURLY
  WAREHOUSE = WH_DEV_XS
  SCHEDULE = '60 MINUTE'
AS
CALL DEV_FS_DB.GOLD.SP_REFRESH_SALES();

--rollback DROP TASK IF EXISTS DEV_FS_DB.GOLD.TSK_REFRESH_SALES_HOURLY;
