--liquibase formatted sql
-- Generated by engine: create view changesets

--changeset engine:view-dev_fs_db_gold_vw_sales_summary-a4040560 runOnChange:true labels:view,create context:create
--comment CREATE view DEV_FS_DB.GOLD.VW_SALES_SUMMARY

CREATE OR REPLACE VIEW DEV_FS_DB.GOLD.VW_SALES_SUMMARY AS
SELECT
    ORDER_DATE,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    SUM(REVENUE_USD)         AS TOTAL_REVENUE
FROM DEV_FS_DB.GOLD.FCT_SALES
GROUP BY ORDER_DATE;

--rollback DROP VIEW IF EXISTS DEV_FS_DB.GOLD.VW_SALES_SUMMARY;
