--liquibase formatted sql
-- Generated by engine: create stored_procedure changesets

--changeset engine:proc-dev_fs_db_dq_sp_dq_assign_dmfs-a2c7d80f runOnChange:true labels:stored_procedure,create context:create splitStatements:false endDelimiter:
--comment CREATE stored_procedure DEV_FS_DB.DQ.SP_DQ_ASSIGN_DMFS

CREATE OR REPLACE PROCEDURE DEV_FS_DB.DQ.SP_DQ_ASSIGN_DMFS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_assigned NUMBER DEFAULT 0;
    c_config CURSOR FOR
        SELECT TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE, TARGET_COLUMN,
               DMF_NAME, SCHEDULE_MINUTES
        FROM DEV_FS_DB.DQ.DQ_DMF_CONFIG
        WHERE IS_ACTIVE = TRUE;
BEGIN
    -- Assign system DMFs to tables/columns based on DQ_DMF_CONFIG entries.
    -- This procedure should be run after initial setup or when config changes.
    FOR cfg IN c_config DO
        LET v_fqn VARCHAR := cfg.TARGET_DATABASE || '.' || cfg.TARGET_SCHEMA || '.' || cfg.TARGET_TABLE;
        LET v_dmf VARCHAR := 'SNOWFLAKE.CORE.' || cfg.DMF_NAME;
        LET v_schedule VARCHAR := cfg.SCHEDULE_MINUTES::VARCHAR || ' MINUTE';

        BEGIN
            IF (cfg.TARGET_COLUMN IS NOT NULL AND cfg.TARGET_COLUMN != '') THEN
                EXECUTE IMMEDIATE
                    'ALTER TABLE ' || v_fqn || ' ALTER COLUMN "' || cfg.TARGET_COLUMN
                    || '" SET DATA METRIC FUNCTION ' || v_dmf
                    || ' ON ("' || cfg.TARGET_COLUMN || '") SCHEDULE = ''' || v_schedule || '''';
            ELSE
                -- Table-level DMFs like FRESHNESS
                EXECUTE IMMEDIATE
                    'ALTER TABLE ' || v_fqn
                    || ' SET DATA METRIC FUNCTION ' || v_dmf
                    || ' ON () SCHEDULE = ''' || v_schedule || '''';
            END IF;
            v_assigned := v_assigned + 1;
        EXCEPTION
            WHEN OTHER THEN
                -- Log but don't fail; DMF may already be assigned or table may not support it
                NULL;
        END;
    END FOR;

    RETURN 'Assigned ' || v_assigned::VARCHAR || ' DMF(s)';
END;
$$;

--rollback DROP PROCEDURE IF EXISTS DEV_FS_DB.DQ.SP_DQ_ASSIGN_DMFS();

--changeset engine:proc-dev_fs_db_dq_sp_dq_execute_all-3fdc6cc1 runOnChange:true labels:stored_procedure,create context:create splitStatements:false endDelimiter:
--comment CREATE stored_procedure DEV_FS_DB.DQ.SP_DQ_EXECUTE_ALL

CREATE OR REPLACE PROCEDURE DEV_FS_DB.DQ.SP_DQ_EXECUTE_ALL(P_ENVIRONMENT VARCHAR, P_TRIGGERED_BY VARCHAR DEFAULT 'SCHEDULED')
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id VARCHAR;
    v_start TIMESTAMP_NTZ;
    v_total NUMBER DEFAULT 0;
    v_passed NUMBER DEFAULT 0;
    v_failed NUMBER DEFAULT 0;
    v_errored NUMBER DEFAULT 0;
    c_rules CURSOR FOR
        SELECT RULE_ID, RULE_NAME, RULE_TYPE, TARGET_DATABASE, TARGET_SCHEMA,
               TARGET_TABLE, TARGET_COLUMN, PARAMETERS
        FROM DEV_FS_DB.DQ.DQ_RULES
        WHERE IS_ACTIVE = TRUE
        ORDER BY SEVERITY DESC, RULE_NAME;
BEGIN
    v_run_id := UUID_STRING();
    v_start := CURRENT_TIMESTAMP();

    INSERT INTO DEV_FS_DB.DQ.DQ_RUN_LOG (RUN_ID, RUN_TYPE, START_TIME, ENVIRONMENT, TRIGGERED_BY)
    VALUES (:v_run_id, :P_TRIGGERED_BY, :v_start, :P_ENVIRONMENT, :P_TRIGGERED_BY);

    FOR rule IN c_rules DO
        v_total := v_total + 1;
        BEGIN
            LET v_result VARIANT;
            CALL DEV_FS_DB.DQ.SP_DQ_EXECUTE_RULE(:rule.RULE_ID, :v_run_id, :P_ENVIRONMENT)
                INTO :v_result;
            IF (v_result:status::VARCHAR = 'PASSED') THEN
                v_passed := v_passed + 1;
            ELSEIF (v_result:status::VARCHAR = 'FAILED') THEN
                v_failed := v_failed + 1;
            ELSE
                v_errored := v_errored + 1;
            END IF;
        EXCEPTION
            WHEN OTHER THEN
                v_errored := v_errored + 1;
                INSERT INTO DEV_FS_DB.DQ.DQ_RESULTS
                    (RESULT_ID, RULE_ID, RUN_ID, RUN_TIMESTAMP, STATUS, ACTUAL_VALUE, EXECUTION_TIME_MS, ENVIRONMENT)
                VALUES (UUID_STRING(), rule.RULE_ID, :v_run_id, CURRENT_TIMESTAMP(), 'ERROR',
                        SUBSTR(SQLERRM, 1, 4096), 0, :P_ENVIRONMENT);
        END;
    END FOR;

    UPDATE DEV_FS_DB.DQ.DQ_RUN_LOG
    SET END_TIME = CURRENT_TIMESTAMP(),
        TOTAL_RULES = :v_total,
        PASSED = :v_passed,
        FAILED = :v_failed,
        ERRORED = :v_errored
    WHERE RUN_ID = :v_run_id;

    RETURN OBJECT_CONSTRUCT(
        'run_id', v_run_id,
        'total', v_total,
        'passed', v_passed,
        'failed', v_failed,
        'errored', v_errored
    );
END;
$$;

--rollback DROP PROCEDURE IF EXISTS DEV_FS_DB.DQ.SP_DQ_EXECUTE_ALL(VARCHAR, VARCHAR);

--changeset engine:proc-dev_fs_db_dq_sp_dq_execute_by_table-cf74677f runOnChange:true labels:stored_procedure,create context:create splitStatements:false endDelimiter:
--comment CREATE stored_procedure DEV_FS_DB.DQ.SP_DQ_EXECUTE_BY_TABLE

CREATE OR REPLACE PROCEDURE DEV_FS_DB.DQ.SP_DQ_EXECUTE_BY_TABLE(P_TARGET_TABLE VARCHAR, P_ENVIRONMENT VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id VARCHAR;
    v_start TIMESTAMP_NTZ;
    v_total NUMBER DEFAULT 0;
    v_passed NUMBER DEFAULT 0;
    v_failed NUMBER DEFAULT 0;
    v_errored NUMBER DEFAULT 0;
    c_rules CURSOR FOR
        SELECT RULE_ID
        FROM DEV_FS_DB.DQ.DQ_RULES
        WHERE IS_ACTIVE = TRUE
          AND UPPER(TARGET_DATABASE || '.' || TARGET_SCHEMA || '.' || TARGET_TABLE) = UPPER(:P_TARGET_TABLE)
        ORDER BY SEVERITY DESC, RULE_NAME;
BEGIN
    v_run_id := UUID_STRING();
    v_start := CURRENT_TIMESTAMP();

    INSERT INTO DEV_FS_DB.DQ.DQ_RUN_LOG (RUN_ID, RUN_TYPE, START_TIME, ENVIRONMENT, TRIGGERED_BY)
    VALUES (:v_run_id, 'AD_HOC', :v_start, :P_ENVIRONMENT, 'TABLE_CHECK: ' || P_TARGET_TABLE);

    FOR rule IN c_rules DO
        v_total := v_total + 1;
        BEGIN
            LET v_result VARIANT;
            CALL DEV_FS_DB.DQ.SP_DQ_EXECUTE_RULE(:rule.RULE_ID, :v_run_id, :P_ENVIRONMENT)
                INTO :v_result;
            IF (v_result:status::VARCHAR = 'PASSED') THEN
                v_passed := v_passed + 1;
            ELSEIF (v_result:status::VARCHAR = 'FAILED') THEN
                v_failed := v_failed + 1;
            ELSE
                v_errored := v_errored + 1;
            END IF;
        EXCEPTION
            WHEN OTHER THEN
                v_errored := v_errored + 1;
        END;
    END FOR;

    UPDATE DEV_FS_DB.DQ.DQ_RUN_LOG
    SET END_TIME = CURRENT_TIMESTAMP(),
        TOTAL_RULES = :v_total,
        PASSED = :v_passed,
        FAILED = :v_failed,
        ERRORED = :v_errored
    WHERE RUN_ID = :v_run_id;

    RETURN OBJECT_CONSTRUCT(
        'run_id', v_run_id,
        'target_table', P_TARGET_TABLE,
        'total', v_total,
        'passed', v_passed,
        'failed', v_failed,
        'errored', v_errored
    );
END;
$$;

--rollback DROP PROCEDURE IF EXISTS DEV_FS_DB.DQ.SP_DQ_EXECUTE_BY_TABLE(VARCHAR, VARCHAR);

--changeset engine:proc-dev_fs_db_dq_sp_dq_execute_rule-285f2507 runOnChange:true labels:stored_procedure,create context:create splitStatements:false endDelimiter:
--comment CREATE stored_procedure DEV_FS_DB.DQ.SP_DQ_EXECUTE_RULE

CREATE OR REPLACE PROCEDURE DEV_FS_DB.DQ.SP_DQ_EXECUTE_RULE(P_RULE_ID VARCHAR, P_RUN_ID VARCHAR, P_ENVIRONMENT VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE
    v_rule_type VARCHAR;
    v_target_db VARCHAR;
    v_target_schema VARCHAR;
    v_target_table VARCHAR;
    v_target_column VARCHAR;
    v_params VARIANT;
    v_fqn VARCHAR;
    v_start TIMESTAMP_NTZ;
    v_status VARCHAR DEFAULT 'PASSED';
    v_actual VARCHAR;
    v_expected VARCHAR;
    v_rows_failed NUMBER DEFAULT 0;
    v_sql VARCHAR;
    v_result_count NUMBER;
BEGIN
    v_start := CURRENT_TIMESTAMP();

    SELECT RULE_TYPE, TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE, TARGET_COLUMN, PARAMETERS
    INTO :v_rule_type, :v_target_db, :v_target_schema, :v_target_table, :v_target_column, :v_params
    FROM DEV_FS_DB.DQ.DQ_RULES
    WHERE RULE_ID = :P_RULE_ID AND IS_ACTIVE = TRUE;

    v_fqn := v_target_db || '.' || v_target_schema || '.' || v_target_table;

    -- Route to the appropriate check based on rule_type
    CASE v_rule_type
        WHEN 'NOT_NULL' THEN
            v_sql := 'SELECT COUNT(*) FROM ' || v_fqn || ' WHERE "' || v_target_column || '" IS NULL';
            EXECUTE IMMEDIATE 'SELECT (' || v_sql || ')' INTO :v_rows_failed;
            v_actual := v_rows_failed::VARCHAR;
            v_expected := '0';
            IF (v_rows_failed > 0) THEN v_status := 'FAILED'; END IF;

        WHEN 'UNIQUE' THEN
            v_sql := 'SELECT COUNT(*) - COUNT(DISTINCT "' || v_target_column || '") FROM ' || v_fqn
                     || ' WHERE "' || v_target_column || '" IS NOT NULL';
            EXECUTE IMMEDIATE 'SELECT (' || v_sql || ')' INTO :v_rows_failed;
            v_actual := v_rows_failed::VARCHAR;
            v_expected := '0';
            IF (v_rows_failed > 0) THEN v_status := 'FAILED'; END IF;

        WHEN 'ACCEPTED_VALUES' THEN
            LET v_values_array ARRAY := v_params:values::ARRAY;
            LET v_values_list VARCHAR := '';
            FOR i IN 0 TO ARRAY_SIZE(v_values_array) - 1 DO
                IF (i > 0) THEN v_values_list := v_values_list || ','; END IF;
                v_values_list := v_values_list || '''' || v_values_array[i]::VARCHAR || '''';
            END FOR;
            v_sql := 'SELECT COUNT(*) FROM ' || v_fqn
                     || ' WHERE "' || v_target_column || '" IS NOT NULL AND "' || v_target_column
                     || '" NOT IN (' || v_values_list || ')';
            EXECUTE IMMEDIATE 'SELECT (' || v_sql || ')' INTO :v_rows_failed;
            v_actual := v_rows_failed::VARCHAR || ' rows with invalid values';
            v_expected := '0 rows with invalid values';
            IF (v_rows_failed > 0) THEN v_status := 'FAILED'; END IF;

        WHEN 'ROW_COUNT_RANGE' THEN
            LET v_min NUMBER := COALESCE(v_params:min::NUMBER, 0);
            LET v_max NUMBER := COALESCE(v_params:max::NUMBER, 999999999999);
            EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || v_fqn INTO :v_result_count;
            v_actual := v_result_count::VARCHAR;
            v_expected := v_min::VARCHAR || ' to ' || v_max::VARCHAR;
            IF (v_result_count < v_min OR v_result_count > v_max) THEN
                v_status := 'FAILED';
                v_rows_failed := v_result_count;
            END IF;

        WHEN 'REFERENTIAL_INTEGRITY' THEN
            LET v_ref_table VARCHAR := v_params:reference_table::VARCHAR;
            LET v_ref_column VARCHAR := v_params:reference_column::VARCHAR;
            v_sql := 'SELECT COUNT(*) FROM ' || v_fqn || ' s LEFT JOIN ' || v_ref_table
                     || ' r ON s."' || v_target_column || '" = r."' || v_ref_column
                     || '" WHERE r."' || v_ref_column || '" IS NULL AND s."'
                     || v_target_column || '" IS NOT NULL';
            EXECUTE IMMEDIATE 'SELECT (' || v_sql || ')' INTO :v_rows_failed;
            v_actual := v_rows_failed::VARCHAR || ' orphaned rows';
            v_expected := '0 orphaned rows';
            IF (v_rows_failed > 0) THEN v_status := 'FAILED'; END IF;

        WHEN 'RECENCY' THEN
            LET v_max_hours NUMBER := COALESCE(v_params:max_hours::NUMBER, 24);
            LET v_hours_since NUMBER;
            v_sql := 'SELECT COALESCE(DATEDIFF(HOUR, MAX("' || v_target_column
                     || '"), CURRENT_TIMESTAMP()), 999999) FROM ' || v_fqn;
            EXECUTE IMMEDIATE 'SELECT (' || v_sql || ')' INTO :v_hours_since;
            v_actual := v_hours_since::VARCHAR || ' hours since last record';
            v_expected := 'Within ' || v_max_hours::VARCHAR || ' hours';
            IF (v_hours_since > v_max_hours) THEN
                v_status := 'FAILED';
                v_rows_failed := 1;
            END IF;

        WHEN 'CUSTOM_SQL' THEN
            LET v_custom_sql VARCHAR := v_params:sql::VARCHAR;
            LET v_expect_value VARCHAR := COALESCE(v_params:expected::VARCHAR, '0');
            LET v_custom_result VARCHAR;
            EXECUTE IMMEDIATE 'SELECT (' || v_custom_sql || ')' INTO :v_custom_result;
            v_actual := v_custom_result;
            v_expected := v_expect_value;
            IF (v_custom_result != v_expect_value) THEN
                v_status := 'FAILED';
                v_rows_failed := 1;
            END IF;

        WHEN 'EXPRESSION' THEN
            LET v_expr VARCHAR := v_params:expression::VARCHAR;
            v_sql := 'SELECT COUNT(*) FROM ' || v_fqn || ' WHERE NOT (' || v_expr || ')';
            EXECUTE IMMEDIATE 'SELECT (' || v_sql || ')' INTO :v_rows_failed;
            v_actual := v_rows_failed::VARCHAR || ' rows violating expression';
            v_expected := '0 rows violating expression';
            IF (v_rows_failed > 0) THEN v_status := 'FAILED'; END IF;

        ELSE
            v_status := 'ERROR';
            v_actual := 'Unknown rule_type: ' || v_rule_type;
    END CASE;

    LET v_exec_ms NUMBER := DATEDIFF(MILLISECOND, v_start, CURRENT_TIMESTAMP());

    INSERT INTO DEV_FS_DB.DQ.DQ_RESULTS
        (RESULT_ID, RULE_ID, RUN_ID, RUN_TIMESTAMP, STATUS, ACTUAL_VALUE, EXPECTED_VALUE,
         ROWS_FAILED, EXECUTION_TIME_MS, ENVIRONMENT)
    VALUES (UUID_STRING(), :P_RULE_ID, :P_RUN_ID, CURRENT_TIMESTAMP(), :v_status,
            :v_actual, :v_expected, :v_rows_failed, :v_exec_ms, :P_ENVIRONMENT);

    RETURN OBJECT_CONSTRUCT('status', v_status, 'actual', v_actual, 'expected', v_expected,
                            'rows_failed', v_rows_failed, 'execution_time_ms', v_exec_ms);
END;
$$;

--rollback DROP PROCEDURE IF EXISTS DEV_FS_DB.DQ.SP_DQ_EXECUTE_RULE(VARCHAR, VARCHAR, VARCHAR);

--changeset engine:proc-dev_fs_db_dq_sp_dq_sync_dmf_results-d1cfd5db runOnChange:true labels:stored_procedure,create context:create splitStatements:false endDelimiter:
--comment CREATE stored_procedure DEV_FS_DB.DQ.SP_DQ_SYNC_DMF_RESULTS

CREATE OR REPLACE PROCEDURE DEV_FS_DB.DQ.SP_DQ_SYNC_DMF_RESULTS(P_ENVIRONMENT VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_synced NUMBER DEFAULT 0;
BEGIN
    -- Sync DMF results from Snowflake's internal monitoring into our unified DQ_RESULTS table.
    -- This creates synthetic results that appear alongside finite rule results in the dashboard.
    -- Note: DATA_QUALITY_MONITORING_RESULTS is available in INFORMATION_SCHEMA for each database.

    MERGE INTO DEV_FS_DB.DQ.DQ_RESULTS tgt
    USING (
        SELECT
            UUID_STRING() AS RESULT_ID,
            'DMF_' || dmr.METRIC_NAME || '_' || dmr.TABLE_NAME || '_' || COALESCE(dmr.COLUMN_NAME, 'TABLE') AS RULE_ID,
            'DMF_SYNC_' || TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS') AS RUN_ID,
            dmr.MEASUREMENT_TIME AS RUN_TIMESTAMP,
            CASE
                WHEN dmr.METRIC_NAME = 'NULL_COUNT' AND dmr.VALUE > 0 THEN 'FAILED'
                WHEN dmr.METRIC_NAME = 'DUPLICATE_COUNT' AND dmr.VALUE > 0 THEN 'FAILED'
                ELSE 'PASSED'
            END AS STATUS,
            dmr.VALUE::VARCHAR AS ACTUAL_VALUE,
            '0' AS EXPECTED_VALUE,
            dmr.VALUE AS ROWS_FAILED,
            0 AS EXECUTION_TIME_MS,
            :P_ENVIRONMENT AS ENVIRONMENT
        FROM TABLE(INFORMATION_SCHEMA.DATA_QUALITY_MONITORING_RESULTS(
            START_TIME => DATEADD(HOUR, -24, CURRENT_TIMESTAMP())
        )) dmr
        WHERE dmr.TABLE_SCHEMA = 'DQ'
           OR dmr.TABLE_SCHEMA IN (
               SELECT DISTINCT TARGET_SCHEMA
               FROM DEV_FS_DB.DQ.DQ_DMF_CONFIG
               WHERE IS_ACTIVE = TRUE
           )
    ) src
    ON tgt.RESULT_ID = src.RESULT_ID
    WHEN NOT MATCHED THEN
        INSERT (RESULT_ID, RULE_ID, RUN_ID, RUN_TIMESTAMP, STATUS, ACTUAL_VALUE,
                EXPECTED_VALUE, ROWS_FAILED, EXECUTION_TIME_MS, ENVIRONMENT)
        VALUES (src.RESULT_ID, src.RULE_ID, src.RUN_ID, src.RUN_TIMESTAMP, src.STATUS,
                src.ACTUAL_VALUE, src.EXPECTED_VALUE, src.ROWS_FAILED,
                src.EXECUTION_TIME_MS, src.ENVIRONMENT);

    v_synced := SQLROWCOUNT;
    RETURN 'Synced ' || v_synced::VARCHAR || ' DMF results';
END;
$$;

--rollback DROP PROCEDURE IF EXISTS DEV_FS_DB.DQ.SP_DQ_SYNC_DMF_RESULTS(VARCHAR);

--changeset engine:proc-dev_fs_db_gold_sp_refresh_sales-7dc464ef runOnChange:true labels:stored_procedure,create context:create splitStatements:false endDelimiter:
--comment CREATE stored_procedure DEV_FS_DB.GOLD.SP_REFRESH_SALES

CREATE OR REPLACE PROCEDURE DEV_FS_DB.GOLD.SP_REFRESH_SALES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO DEV_FS_DB.GOLD.FCT_SALES (ORDER_ID, CUSTOMER_SK, ORDER_DATE, REVENUE_USD)
    SELECT
        ORDER_ID,
        NULL AS CUSTOMER_SK,
        ORDER_DATE::DATE,
        ORDER_AMOUNT
    FROM DEV_FS_DB.BRONZE.RAW_ORDERS
    WHERE LOADED_AT > (SELECT COALESCE(MAX(LOADED_AT), '1900-01-01') FROM DEV_FS_DB.GOLD.FCT_SALES);
    RETURN 'OK';
END;
$$;

--rollback DROP PROCEDURE IF EXISTS DEV_FS_DB.GOLD.SP_REFRESH_SALES();
