--liquibase formatted sql
-- Generated by engine: create stage changesets

--changeset engine:stage-dev_fs_db_bronze_stg_orders_landing-b5b6f8eb runOnChange:true labels:stage,create context:create
--comment CREATE stage DEV_FS_DB.BRONZE.STG_ORDERS_LANDING

CREATE OR REPLACE STAGE DEV_FS_DB.BRONZE.STG_ORDERS_LANDING
  URL = 's3://my-data-lake-dev/orders/'
  STORAGE_INTEGRATION = SI_S3_DEV
  FILE_FORMAT = ( FORMAT_NAME = DEV_FS_DB.BRONZE.FF_CSV_STANDARD );

--rollback DROP STAGE IF EXISTS DEV_FS_DB.BRONZE.STG_ORDERS_LANDING;
