--liquibase formatted sql
-- Generated by engine: create dynamic_table changesets

--changeset engine:dyntable-dev_fs_db_gold_dt_sales_daily-01d8a452 runOnChange:true labels:dynamic_table,create context:create
--comment CREATE dynamic_table DEV_FS_DB.GOLD.DT_SALES_DAILY

CREATE OR REPLACE DYNAMIC TABLE DEV_FS_DB.GOLD.DT_SALES_DAILY
  TARGET_LAG = '1 hour'
  WAREHOUSE = WH_DEV_XS
  REFRESH_MODE = AUTO
AS
SELECT
    ORDER_DATE,
    COUNT(*)         AS ORDERS,
    SUM(REVENUE_USD) AS REVENUE
FROM DEV_FS_DB.GOLD.FCT_SALES
GROUP BY ORDER_DATE;

--rollback DROP DYNAMIC TABLE IF EXISTS DEV_FS_DB.GOLD.DT_SALES_DAILY;
