--liquibase formatted sql
-- Generated by engine: grant grant changesets

--changeset engine:grant-dq-c74fbd7c runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT ON TABLE DEV_FS_DB.DQ.DQ_RULES TO ROLE ROLE_DQ_READER;

--changeset engine:grant-dq-c7a3427c runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT ON TABLE DEV_FS_DB.DQ.DQ_RESULTS TO ROLE ROLE_DQ_READER;

--changeset engine:grant-dq-09e04f1b runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT ON TABLE DEV_FS_DB.DQ.DQ_RUN_LOG TO ROLE ROLE_DQ_READER;

--changeset engine:grant-dq-8574e69f runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT ON TABLE DEV_FS_DB.DQ.DQ_DMF_CONFIG TO ROLE ROLE_DQ_READER;

--changeset engine:grant-dq-dd9d9b2e runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT, INSERT, UPDATE ON TABLE DEV_FS_DB.DQ.DQ_RULES TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-1facb18a runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT, INSERT, UPDATE ON TABLE DEV_FS_DB.DQ.DQ_RESULTS TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-337d08f8 runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT, INSERT, UPDATE ON TABLE DEV_FS_DB.DQ.DQ_RUN_LOG TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-1e0676a4 runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT SELECT, INSERT, UPDATE ON TABLE DEV_FS_DB.DQ.DQ_DMF_CONFIG TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-1243def5 runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT USAGE ON PROCEDURE DEV_FS_DB.DQ.SP_DQ_EXECUTE_ALL(VARCHAR, VARCHAR) TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-33d82b4c runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT USAGE ON PROCEDURE DEV_FS_DB.DQ.SP_DQ_EXECUTE_RULE(VARCHAR, VARCHAR, VARCHAR) TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-2018f24a runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT USAGE ON PROCEDURE DEV_FS_DB.DQ.SP_DQ_EXECUTE_BY_TABLE(VARCHAR, VARCHAR) TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-6d4d6e7e runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT USAGE ON PROCEDURE DEV_FS_DB.DQ.SP_DQ_SYNC_DMF_RESULTS(VARCHAR) TO ROLE ROLE_DQ_WRITER;

--changeset engine:grant-dq-04ef4a40 runOnChange:true labels:grant,grant context:grant
--comment GRANT grant dq

GRANT USAGE ON PROCEDURE DEV_FS_DB.DQ.SP_DQ_ASSIGN_DMFS() TO ROLE ROLE_DQ_WRITER;
