--liquibase formatted sql
-- Generated by engine: seed dq_seed changesets

--changeset engine:dq-seed-dq_rules-dfb72b58 runOnChange:true labels:dq_seed,seed context:seed
--comment SEED dq_seed DEV_FS_DB.DQ.DQ_RULES

MERGE INTO DEV_FS_DB.DQ.DQ_RULES AS tgt
USING (
  SELECT 'raw_customers_customer_id_not_null', 'raw_customers_customer_id_not_null', 'NOT_NULL', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_CUSTOMERS', 'CUSTOMER_ID', 'CRITICAL', NULL, 'CUSTOMER_ID must never be null', 'data-engineering'
  UNION ALL
  SELECT 'raw_customers_customer_id_unique', 'raw_customers_customer_id_unique', 'UNIQUE', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_CUSTOMERS', 'CUSTOMER_ID', 'CRITICAL', NULL, 'CUSTOMER_ID must be unique', 'data-engineering'
  UNION ALL
  SELECT 'raw_customers_has_data', 'raw_customers_has_data', 'ROW_COUNT_RANGE', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_CUSTOMERS', NULL, 'WARNING', PARSE_JSON('{"min": 1}'), 'RAW_CUSTOMERS must not be empty', 'data-engineering'
  UNION ALL
  SELECT 'raw_orders_order_id_not_null', 'raw_orders_order_id_not_null', 'NOT_NULL', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_ORDERS', 'ORDER_ID', 'CRITICAL', NULL, 'ORDER_ID must never be null - it is the primary business key', 'data-engineering'
  UNION ALL
  SELECT 'raw_orders_order_id_unique', 'raw_orders_order_id_unique', 'UNIQUE', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_ORDERS', 'ORDER_ID', 'CRITICAL', NULL, 'ORDER_ID must be unique across all records', 'data-engineering'
  UNION ALL
  SELECT 'raw_orders_status_accepted_values', 'raw_orders_status_accepted_values', 'ACCEPTED_VALUES', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_ORDERS', 'ORDER_STATUS', 'WARNING', PARSE_JSON('{"values": ["PENDING", "CONFIRMED", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"]}'), 'ORDER_STATUS must be one of the known lifecycle states', 'data-engineering'
  UNION ALL
  SELECT 'raw_orders_has_data', 'raw_orders_has_data', 'ROW_COUNT_RANGE', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_ORDERS', NULL, 'CRITICAL', PARSE_JSON('{"min": 1}'), 'RAW_ORDERS must contain at least 1 row (table should never be empty)', 'data-engineering'
  UNION ALL
  SELECT 'raw_orders_amount_positive', 'raw_orders_amount_positive', 'EXPRESSION', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_ORDERS', 'ORDER_AMOUNT', 'WARNING', PARSE_JSON('{"expression": "\"ORDER_AMOUNT\" >= 0 OR \"ORDER_STATUS\" IN (''CANCELLED'', ''RETURNED'')"}'), 'ORDER_AMOUNT should be positive for non-cancelled orders', 'data-engineering'
  UNION ALL
  SELECT 'raw_orders_freshness', 'raw_orders_freshness', 'RECENCY', 'engine', 'DEV_FS_DB', 'BRONZE', 'RAW_ORDERS', 'LOADED_AT', 'WARNING', PARSE_JSON('{"max_hours": 6}'), 'Data should be loaded within the last 6 hours', 'data-engineering'
  UNION ALL
  SELECT 'fct_sales_order_id_not_null', 'fct_sales_order_id_not_null', 'NOT_NULL', 'engine', 'DEV_FS_DB', 'GOLD', 'FCT_SALES', 'ORDER_ID', 'CRITICAL', NULL, 'ORDER_ID is the business key and must never be null', 'analytics-team'
  UNION ALL
  SELECT 'fct_sales_order_id_unique', 'fct_sales_order_id_unique', 'UNIQUE', 'engine', 'DEV_FS_DB', 'GOLD', 'FCT_SALES', 'ORDER_ID', 'CRITICAL', NULL, 'ORDER_ID must be unique in the fact table (no duplicate facts)', 'analytics-team'
  UNION ALL
  SELECT 'fct_sales_revenue_non_negative', 'fct_sales_revenue_non_negative', 'EXPRESSION', 'engine', 'DEV_FS_DB', 'GOLD', 'FCT_SALES', 'REVENUE_USD', 'WARNING', PARSE_JSON('{"expression": "\"REVENUE_USD\" >= 0 OR \"REVENUE_USD\" IS NULL"}'), 'Revenue should never be negative', 'analytics-team'
  UNION ALL
  SELECT 'fct_sales_referential_integrity_orders', 'fct_sales_referential_integrity_orders', 'REFERENTIAL_INTEGRITY', 'engine', 'DEV_FS_DB', 'GOLD', 'FCT_SALES', 'ORDER_ID', 'WARNING', PARSE_JSON('{"reference_table": "DEV_FS_DB.BRONZE.RAW_ORDERS", "reference_column": "ORDER_ID"}'), 'Every ORDER_ID in FCT_SALES must exist in RAW_ORDERS', 'analytics-team'
  UNION ALL
  SELECT 'fct_sales_freshness', 'fct_sales_freshness', 'RECENCY', 'engine', 'DEV_FS_DB', 'GOLD', 'FCT_SALES', 'LOADED_AT', 'WARNING', PARSE_JSON('{"max_hours": 3}'), 'Fact table should be refreshed within the last 3 hours', 'analytics-team'
  UNION ALL
  SELECT 'fct_sales_row_count_sanity', 'fct_sales_row_count_sanity', 'ROW_COUNT_RANGE', 'engine', 'DEV_FS_DB', 'GOLD', 'FCT_SALES', NULL, 'INFO', PARSE_JSON('{"min": 1, "max": 100000000}'), 'FCT_SALES should have a reasonable number of rows', 'analytics-team'
) AS src (RULE_ID, RULE_NAME, RULE_TYPE, SOURCE, TARGET_DATABASE, TARGET_SCHEMA,
          TARGET_TABLE, TARGET_COLUMN, SEVERITY, PARAMETERS, DESCRIPTION, OWNER)
ON tgt.RULE_ID = src.RULE_ID AND tgt.SOURCE = 'engine'
WHEN MATCHED THEN UPDATE SET
    RULE_NAME = src.RULE_NAME,
    RULE_TYPE = src.RULE_TYPE,
    TARGET_DATABASE = src.TARGET_DATABASE,
    TARGET_SCHEMA = src.TARGET_SCHEMA,
    TARGET_TABLE = src.TARGET_TABLE,
    TARGET_COLUMN = src.TARGET_COLUMN,
    SEVERITY = src.SEVERITY,
    PARAMETERS = src.PARAMETERS,
    DESCRIPTION = src.DESCRIPTION,
    OWNER = src.OWNER,
    IS_ACTIVE = TRUE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (RULE_ID, RULE_NAME, RULE_TYPE, SOURCE, TARGET_DATABASE, TARGET_SCHEMA,
     TARGET_TABLE, TARGET_COLUMN, SEVERITY, PARAMETERS, DESCRIPTION, OWNER, IS_ACTIVE)
VALUES
    (src.RULE_ID, src.RULE_NAME, src.RULE_TYPE, src.SOURCE, src.TARGET_DATABASE,
     src.TARGET_SCHEMA, src.TARGET_TABLE, src.TARGET_COLUMN, src.SEVERITY,
     src.PARAMETERS, src.DESCRIPTION, src.OWNER, TRUE);


UPDATE DEV_FS_DB.DQ.DQ_RULES
SET IS_ACTIVE = FALSE, UPDATED_AT = CURRENT_TIMESTAMP()
WHERE SOURCE = 'engine'
  AND IS_ACTIVE = TRUE
  AND RULE_ID NOT IN ('raw_customers_customer_id_not_null', 'raw_customers_customer_id_unique', 'raw_customers_has_data', 'raw_orders_order_id_not_null', 'raw_orders_order_id_unique', 'raw_orders_status_accepted_values', 'raw_orders_has_data', 'raw_orders_amount_positive', 'raw_orders_freshness', 'fct_sales_order_id_not_null', 'fct_sales_order_id_unique', 'fct_sales_revenue_non_negative', 'fct_sales_referential_integrity_orders', 'fct_sales_freshness', 'fct_sales_row_count_sanity');
