CREATE OR REPLACE PROCEDURE ${DATABASE}.GOLD.SP_REFRESH_SALES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO ${DATABASE}.GOLD.FCT_SALES (ORDER_ID, CUSTOMER_SK, ORDER_DATE, REVENUE_USD)
    SELECT
        ORDER_ID,
        NULL AS CUSTOMER_SK,
        ORDER_DATE::DATE,
        ORDER_AMOUNT
    FROM ${DATABASE}.BRONZE.RAW_ORDERS
    WHERE LOADED_AT > (SELECT COALESCE(MAX(LOADED_AT), '1900-01-01') FROM ${DATABASE}.GOLD.FCT_SALES);
    RETURN 'OK';
END;
$$
